# Generated by Django 5.1 on 2025-01-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_authentication', '0002_customuser_passport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
