# Generated by Django 5.1 on 2025-01-31 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_authentication', '0003_customuser_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
